---
- name: Quick Couchbase setup with transactions bucket and Python SDK
  hosts: all
  sudo: yes
  tasks:
  - name: Install python dependencies
    yum: name={{item}} state=latest update_cache=yes
    with_items:
    - epel-release
    - python-httplib2
    - python-pip
    - python-devel
    - gcc
    - libselinux-python

  - name: Check if deps exists
    stat: path=/vagrant/deps
    register: deps_exists

  - name: Create deps Directory
    file: path=/vagrant/deps state=directory
    when: deps_exists.stat.exists == False

  - name: Check if Couchbase RPM exists
    stat: path=/vagrant/deps/couchbase-server-enterprise-4.0.0-beta-centos6.x86_64.rpm
    register: couchbase_rpm

  - name: Download Couchbase RPM
    get_url: url=http://packages.couchbase.com/releases/4.0.0-beta/couchbase-server-enterprise-4.0.0-beta-centos6.x86_64.rpm dest=/vagrant/deps/
    when: couchbase_rpm.stat.exists == False

  - name: Install Couchbase RPM
    yum: name=/vagrant/deps/couchbase-server-enterprise-4.0.0-beta-centos6.x86_64.rpm state=present
  
  - name: Wait for Couchbase initilization
    wait_for: port=8091 delay=2

  - name: Configure Base Couchbase Server
    shell: /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-username=couchbase --cluster-init-password=couchbase --cluster-init-port=8091 --cluster-init-ramsize=796 --services=data,index,query
    register: couchbase_config
    ignore_errors: True

  - name: Configure transactions Bucket
    shell: /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 -u couchbase -p couchbase --bucket=transactions --bucket-type=couchbase --bucket-ramsize=796 --bucket-replica=1
    when: couchbase_config is defined

  - name: Copy Couchbase C Library repo file
    copy: src=couchbase.repo dest=/etc/yum.repos.d/couchbase.repo
    
  - name: Install libcouchbase
    yum: name={{item}} state=latest
    with_items:
    - libcouchbase2-libevent
    - libcouchbase-devel
    - libcouchbase2-bin

  - name: Install Couchbase Python SDK
    pip: name=couchbase state=latest
