---
- name: Install Kafka
  hosts: all
  sudo: yes
  tasks:
  - name: Install Java
    yum: name=java-1.7.0-openjdk.x86_64 state=latest

  - name: Check if Kafka TAR exists
    stat: path=/vagrant/deps/kafka_2.10-0.8.2.0.tgz
    register: kafka_tar

  - name: Download Kafka TAR
    get_url: url=http://apache.mirrors.pair.com/kafka/0.8.2.0/kafka_2.10-0.8.2.0.tgz  dest=/vagrant/deps/
    when: kafka_tar.stat.exists == False

  - name: Unpack Kafka
    unarchive: src=/vagrant/deps/kafka_2.10-0.8.2.0.tgz dest=/opt/ copy=no

  - name: Start Zookeeper Server
    shell: /opt/kafka_2.10-0.8.2.0/bin/zookeeper-server-start.sh -daemon /opt/kafka_2.10-0.8.2.0/config/zookeeper.properties

  - name: Start Kafka Server
    shell: /opt/kafka_2.10-0.8.2.0/bin/kafka-server-start.sh -daemon /opt/kafka_2.10-0.8.2.0/config/server.properties

  - name: Create transactions topic
    shell: /opt/kafka_2.10-0.8.2.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic transactions
