# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
  end

  config.vm.define "couchbase" do |vmconfig|
    vmconfig.vm.box = "chef/centos-6.6"
    vmconfig.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
    end

    vmconfig.vm.hostname = "couchbase.vagrant"
    vmconfig.vm.network :private_network, ip: "192.168.56.40"
     
    vmconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "couchbase.yml"
    end
  end
   
  config.vm.define "kafka" do |vmconfig|
    vmconfig.vm.box = "chef/centos-6.6"
    vmconfig.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
    end

    vmconfig.vm.hostname = "kafka.vagrant"
    vmconfig.vm.network :private_network, ip: "192.168.56.41"
     
    vmconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "kafka.yml"
    end
  end
end
